//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:27:16 PM CET 
//


package cablelabs.md.xsd.title._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import cablelabs.md.xsd.core._3.PersonType;


/**
 * 
 * 				A collection of Title metadata which is specified in multiple lanaguages for localization.
 * 			
 * 
 * <p>Java class for LocalizableTitleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalizableTitleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TitleSortName" type="{urn:cablelabs:md:xsd:title:3.0}TitleSortType" minOccurs="0"/>
 *         &lt;element name="TitleBrief" type="{urn:cablelabs:md:xsd:title:3.0}TitleBriefType"/>
 *         &lt;element name="TitleMedium" type="{urn:cablelabs:md:xsd:title:3.0}TitleMediumType"/>
 *         &lt;element name="TitleLong" type="{urn:cablelabs:md:xsd:title:3.0}TitleLongType"/>
 *         &lt;element name="SummaryShort" type="{urn:cablelabs:md:xsd:title:3.0}SummaryShortType"/>
 *         &lt;element name="SummaryMedium" type="{urn:cablelabs:md:xsd:title:3.0}SummaryMediumType" minOccurs="0"/>
 *         &lt;element name="SummaryLong" type="{urn:cablelabs:md:xsd:title:3.0}SummaryLongType" minOccurs="0"/>
 *         &lt;element name="ActorDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="Actor" type="{urn:cablelabs:md:xsd:core:3.0}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WriterDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="Writer" type="{urn:cablelabs:md:xsd:core:3.0}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DirectorDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="Director" type="{urn:cablelabs:md:xsd:core:3.0}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProducerDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="Producer" type="{urn:cablelabs:md:xsd:core:3.0}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StudioDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="RecordingArtist" type="{urn:cablelabs:md:xsd:title:3.0}RecordingArtistType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RecordingArtistDisplay" type="{urn:cablelabs:md:xsd:core:3.0}ListDisplayType" minOccurs="0"/>
 *         &lt;element name="SongTitle" type="{urn:cablelabs:md:xsd:title:3.0}SongTitleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EpisodeName" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="EpisodeID" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="Chapter" type="{urn:cablelabs:md:xsd:title:3.0}ChapterType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalizableTitleType", propOrder = {
    "titleSortName",
    "titleBrief",
    "titleMedium",
    "titleLong",
    "summaryShort",
    "summaryMedium",
    "summaryLong",
    "actorDisplay",
    "actor",
    "writerDisplay",
    "writer",
    "directorDisplay",
    "director",
    "producerDisplay",
    "producer",
    "studioDisplay",
    "recordingArtist",
    "recordingArtistDisplay",
    "songTitle",
    "episodeName",
    "episodeID",
    "chapter"
})
public class LocalizableTitleType {

    @XmlElement(name = "TitleSortName")
    protected String titleSortName;
    @XmlElement(name = "TitleBrief", required = true)
    protected String titleBrief;
    @XmlElement(name = "TitleMedium", required = true)
    protected String titleMedium;
    @XmlElement(name = "TitleLong", required = true)
    protected String titleLong;
    @XmlElement(name = "SummaryShort", required = true)
    protected String summaryShort;
    @XmlElement(name = "SummaryMedium")
    protected String summaryMedium;
    @XmlElement(name = "SummaryLong")
    protected String summaryLong;
    @XmlElement(name = "ActorDisplay")
    protected String actorDisplay;
    @XmlElement(name = "Actor")
    protected List<PersonType> actor;
    @XmlElement(name = "WriterDisplay")
    protected String writerDisplay;
    @XmlElement(name = "Writer")
    protected List<PersonType> writer;
    @XmlElement(name = "DirectorDisplay")
    protected String directorDisplay;
    @XmlElement(name = "Director")
    protected List<PersonType> director;
    @XmlElement(name = "ProducerDisplay")
    protected String producerDisplay;
    @XmlElement(name = "Producer")
    protected List<PersonType> producer;
    @XmlElement(name = "StudioDisplay")
    protected String studioDisplay;
    @XmlElement(name = "RecordingArtist")
    protected List<String> recordingArtist;
    @XmlElement(name = "RecordingArtistDisplay")
    protected String recordingArtistDisplay;
    @XmlElement(name = "SongTitle")
    protected List<String> songTitle;
    @XmlElement(name = "EpisodeName")
    protected String episodeName;
    @XmlElement(name = "EpisodeID")
    protected String episodeID;
    @XmlElement(name = "Chapter")
    protected List<ChapterType> chapter;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the titleSortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleSortName() {
        return titleSortName;
    }

    /**
     * Sets the value of the titleSortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleSortName(String value) {
        this.titleSortName = value;
    }

    /**
     * Gets the value of the titleBrief property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleBrief() {
        return titleBrief;
    }

    /**
     * Sets the value of the titleBrief property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleBrief(String value) {
        this.titleBrief = value;
    }

    /**
     * Gets the value of the titleMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleMedium() {
        return titleMedium;
    }

    /**
     * Sets the value of the titleMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleMedium(String value) {
        this.titleMedium = value;
    }

    /**
     * Gets the value of the titleLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLong() {
        return titleLong;
    }

    /**
     * Sets the value of the titleLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLong(String value) {
        this.titleLong = value;
    }

    /**
     * Gets the value of the summaryShort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryShort() {
        return summaryShort;
    }

    /**
     * Sets the value of the summaryShort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryShort(String value) {
        this.summaryShort = value;
    }

    /**
     * Gets the value of the summaryMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryMedium() {
        return summaryMedium;
    }

    /**
     * Sets the value of the summaryMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryMedium(String value) {
        this.summaryMedium = value;
    }

    /**
     * Gets the value of the summaryLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryLong() {
        return summaryLong;
    }

    /**
     * Sets the value of the summaryLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryLong(String value) {
        this.summaryLong = value;
    }

    /**
     * Gets the value of the actorDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActorDisplay() {
        return actorDisplay;
    }

    /**
     * Sets the value of the actorDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActorDisplay(String value) {
        this.actorDisplay = value;
    }

    /**
     * Gets the value of the actor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getActor() {
        if (actor == null) {
            actor = new ArrayList<PersonType>();
        }
        return this.actor;
    }

    /**
     * Gets the value of the writerDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWriterDisplay() {
        return writerDisplay;
    }

    /**
     * Sets the value of the writerDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWriterDisplay(String value) {
        this.writerDisplay = value;
    }

    /**
     * Gets the value of the writer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the writer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWriter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getWriter() {
        if (writer == null) {
            writer = new ArrayList<PersonType>();
        }
        return this.writer;
    }

    /**
     * Gets the value of the directorDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorDisplay() {
        return directorDisplay;
    }

    /**
     * Sets the value of the directorDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorDisplay(String value) {
        this.directorDisplay = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the director property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getDirector() {
        if (director == null) {
            director = new ArrayList<PersonType>();
        }
        return this.director;
    }

    /**
     * Gets the value of the producerDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerDisplay() {
        return producerDisplay;
    }

    /**
     * Sets the value of the producerDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerDisplay(String value) {
        this.producerDisplay = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the producer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProducer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getProducer() {
        if (producer == null) {
            producer = new ArrayList<PersonType>();
        }
        return this.producer;
    }

    /**
     * Gets the value of the studioDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudioDisplay() {
        return studioDisplay;
    }

    /**
     * Sets the value of the studioDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudioDisplay(String value) {
        this.studioDisplay = value;
    }

    /**
     * Gets the value of the recordingArtist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordingArtist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordingArtist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRecordingArtist() {
        if (recordingArtist == null) {
            recordingArtist = new ArrayList<String>();
        }
        return this.recordingArtist;
    }

    /**
     * Gets the value of the recordingArtistDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordingArtistDisplay() {
        return recordingArtistDisplay;
    }

    /**
     * Sets the value of the recordingArtistDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordingArtistDisplay(String value) {
        this.recordingArtistDisplay = value;
    }

    /**
     * Gets the value of the songTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the songTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSongTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSongTitle() {
        if (songTitle == null) {
            songTitle = new ArrayList<String>();
        }
        return this.songTitle;
    }

    /**
     * Gets the value of the episodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeName() {
        return episodeName;
    }

    /**
     * Sets the value of the episodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeName(String value) {
        this.episodeName = value;
    }

    /**
     * Gets the value of the episodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeID() {
        return episodeID;
    }

    /**
     * Sets the value of the episodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeID(String value) {
        this.episodeID = value;
    }

    /**
     * Gets the value of the chapter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chapter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChapter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChapterType }
     * 
     * 
     */
    public List<ChapterType> getChapter() {
        if (chapter == null) {
            chapter = new ArrayList<ChapterType>();
        }
        return this.chapter;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
