//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:27:16 PM CET 
//


package cablelabs.md.xsd.title._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import cablelabs.md.xsd.core._3.AssetType;
import cablelabs.md.xsd.core._3.RatingType;


/**
 * <p>Java class for TitleBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TitleBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:cablelabs:md:xsd:core:3.0}AssetType">
 *       &lt;sequence>
 *         &lt;element name="LocalizableTitle" type="{urn:cablelabs:md:xsd:title:3.0}LocalizableTitleType" maxOccurs="unbounded"/>
 *         &lt;element name="Rating" type="{urn:cablelabs:md:xsd:core:3.0}RatingType" maxOccurs="unbounded"/>
 *         &lt;element name="Audience" type="{urn:cablelabs:md:xsd:core:3.0}AudienceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Advisory" type="{urn:cablelabs:md:xsd:core:3.0}AdvisoryType" maxOccurs="6" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TitleBaseType", propOrder = {
    "localizableTitle",
    "rating",
    "audience",
    "advisory"
})
@XmlSeeAlso({
    TitleType.class
})
public class TitleBaseType
    extends AssetType
{

    @XmlElement(name = "LocalizableTitle", required = true)
    protected List<LocalizableTitleType> localizableTitle;
    @XmlElement(name = "Rating", required = true)
    protected List<RatingType> rating;
    @XmlElement(name = "Audience")
    protected List<String> audience;
    @XmlElement(name = "Advisory")
    protected List<String> advisory;

    /**
     * Gets the value of the localizableTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizableTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizableTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizableTitleType }
     * 
     * 
     */
    public List<LocalizableTitleType> getLocalizableTitle() {
        if (localizableTitle == null) {
            localizableTitle = new ArrayList<LocalizableTitleType>();
        }
        return this.localizableTitle;
    }

    /**
     * Gets the value of the rating property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rating property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRating().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatingType }
     * 
     * 
     */
    public List<RatingType> getRating() {
        if (rating == null) {
            rating = new ArrayList<RatingType>();
        }
        return this.rating;
    }

    /**
     * Gets the value of the audience property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audience property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudience().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAudience() {
        if (audience == null) {
            audience = new ArrayList<String>();
        }
        return this.audience;
    }

    /**
     * Gets the value of the advisory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advisory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvisory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdvisory() {
        if (advisory == null) {
            advisory = new ArrayList<String>();
        }
        return this.advisory;
    }

}
