//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:27:16 PM CET 
//


package cablelabs.md.xsd.title._3;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TitleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TitleType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:cablelabs:md:xsd:title:3.0}TitleBaseType">
 *       &lt;sequence>
 *         &lt;element name="IsClosedCaptioning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DisplayRunTime" type="{urn:cablelabs:md:xsd:core:3.0}DisplayRunTimeType"/>
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="CountryOfOrigin" type="{urn:cablelabs:md:xsd:core:3.0}CountryType" minOccurs="0"/>
 *         &lt;element name="Genre" type="{urn:cablelabs:md:xsd:core:3.0}GenreType" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="ShowType" type="{urn:cablelabs:md:xsd:core:3.0}ShowTypeType"/>
 *         &lt;element name="IsSeasonPremiere" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsSeasonFinale" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsEncryptionRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="BoxOffice" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ProgrammerCallLetters" type="{urn:cablelabs:md:xsd:core:3.0}ProgrammerCallLettersType" minOccurs="0"/>
 *         &lt;element name="LinearBroadcastDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TitleType", propOrder = {
    "isClosedCaptioning",
    "displayRunTime",
    "year",
    "countryOfOrigin",
    "genre",
    "showType",
    "isSeasonPremiere",
    "isSeasonFinale",
    "isEncryptionRequired",
    "boxOffice",
    "programmerCallLetters",
    "linearBroadcastDate"
})
public class TitleType
    extends TitleBaseType
{

    @XmlElement(name = "IsClosedCaptioning")
    protected Boolean isClosedCaptioning;
    @XmlElement(name = "DisplayRunTime", required = true)
    protected String displayRunTime;
    @XmlElement(name = "Year")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;
    @XmlElement(name = "CountryOfOrigin")
    protected String countryOfOrigin;
    @XmlElement(name = "Genre")
    protected List<String> genre;
    @XmlElement(name = "ShowType", required = true)
    protected String showType;
    @XmlElement(name = "IsSeasonPremiere")
    protected Boolean isSeasonPremiere;
    @XmlElement(name = "IsSeasonFinale")
    protected Boolean isSeasonFinale;
    @XmlElement(name = "IsEncryptionRequired")
    protected Boolean isEncryptionRequired;
    @XmlElement(name = "BoxOffice")
    protected BigInteger boxOffice;
    @XmlElement(name = "ProgrammerCallLetters")
    protected String programmerCallLetters;
    @XmlElement(name = "LinearBroadcastDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar linearBroadcastDate;

    /**
     * Gets the value of the isClosedCaptioning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsClosedCaptioning() {
        return isClosedCaptioning;
    }

    /**
     * Sets the value of the isClosedCaptioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsClosedCaptioning(Boolean value) {
        this.isClosedCaptioning = value;
    }

    /**
     * Gets the value of the displayRunTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayRunTime() {
        return displayRunTime;
    }

    /**
     * Sets the value of the displayRunTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayRunTime(String value) {
        this.displayRunTime = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYear(XMLGregorianCalendar value) {
        this.year = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genre property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenre().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGenre() {
        if (genre == null) {
            genre = new ArrayList<String>();
        }
        return this.genre;
    }

    /**
     * Gets the value of the showType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowType() {
        return showType;
    }

    /**
     * Sets the value of the showType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowType(String value) {
        this.showType = value;
    }

    /**
     * Gets the value of the isSeasonPremiere property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSeasonPremiere() {
        return isSeasonPremiere;
    }

    /**
     * Sets the value of the isSeasonPremiere property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSeasonPremiere(Boolean value) {
        this.isSeasonPremiere = value;
    }

    /**
     * Gets the value of the isSeasonFinale property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSeasonFinale() {
        return isSeasonFinale;
    }

    /**
     * Sets the value of the isSeasonFinale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSeasonFinale(Boolean value) {
        this.isSeasonFinale = value;
    }

    /**
     * Gets the value of the isEncryptionRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEncryptionRequired() {
        return isEncryptionRequired;
    }

    /**
     * Sets the value of the isEncryptionRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEncryptionRequired(Boolean value) {
        this.isEncryptionRequired = value;
    }

    /**
     * Gets the value of the boxOffice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBoxOffice() {
        return boxOffice;
    }

    /**
     * Sets the value of the boxOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBoxOffice(BigInteger value) {
        this.boxOffice = value;
    }

    /**
     * Gets the value of the programmerCallLetters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammerCallLetters() {
        return programmerCallLetters;
    }

    /**
     * Sets the value of the programmerCallLetters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammerCallLetters(String value) {
        this.programmerCallLetters = value;
    }

    /**
     * Gets the value of the linearBroadcastDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLinearBroadcastDate() {
        return linearBroadcastDate;
    }

    /**
     * Sets the value of the linearBroadcastDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLinearBroadcastDate(XMLGregorianCalendar value) {
        this.linearBroadcastDate = value;
    }

}
