//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.core._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * An alternate identifier for an asset
 * 
 * <p>Java class for AlternateIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlternateIdType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cablelabs:md:xsd:core:3.0>NonEmptyStringType">
 *       &lt;attribute name="identifierSystem" use="required" type="{urn:cablelabs:md:xsd:core:3.0}IdentifierSystemType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlternateIdType", propOrder = {
    "value"
})
public class AlternateIdType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "identifierSystem", required = true)
    protected String identifierSystem;

    /**
     * A non-empty (at least 1 character) string
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the identifierSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifierSystem() {
        return identifierSystem;
    }

    /**
     * Sets the value of the identifierSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifierSystem(String value) {
        this.identifierSystem = value;
    }

}
