//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.core._3;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import cablelabs.md.xsd.content._3.ContentAssetType;


/**
 * An abstract base type from which all other MD3.0 assets are derived.
 * 
 * <p>Java class for AssetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlternateId" type="{urn:cablelabs:md:xsd:core:3.0}AlternateIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProviderQAContact" type="{urn:cablelabs:md:xsd:core:3.0}ContactInfoType" minOccurs="0"/>
 *         &lt;element name="AssetName" type="{urn:cablelabs:md:xsd:core:3.0}AssetNameType" minOccurs="0"/>
 *         &lt;element name="Product" type="{urn:cablelabs:md:xsd:core:3.0}ProductType" minOccurs="0"/>
 *         &lt;element name="Provider" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="Description" type="{urn:cablelabs:md:xsd:core:3.0}DescriptionType" minOccurs="0"/>
 *         &lt;element name="Ext" type="{urn:cablelabs:md:xsd:core:3.0}ExtType" minOccurs="0"/>
 *         &lt;element name="MasterSourceRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uriId" use="required" type="{urn:cablelabs:md:xsd:core:3.0}URIIdType" />
 *       &lt;attribute name="providerVersionNum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="internalVersionNum" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="creationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="startDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="notifyURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="lastModifiedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="eTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{urn:cablelabs:md:xsd:core:3.0}StateType" />
 *       &lt;attribute name="stateDetail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetType", propOrder = {
    "alternateId",
    "providerQAContact",
    "assetName",
    "product",
    "provider",
    "description",
    "ext",
    "masterSourceRef"
})
@XmlSeeAlso({
    ContentAssetType.class
})
public abstract class AssetType {

    @XmlElement(name = "AlternateId")
    protected List<AlternateIdType> alternateId;
    @XmlElement(name = "ProviderQAContact")
    protected String providerQAContact;
    @XmlElement(name = "AssetName")
    protected AssetNameType assetName;
    @XmlElement(name = "Product")
    protected ProductType product;
    @XmlElement(name = "Provider")
    protected String provider;
    @XmlElement(name = "Description")
    protected DescriptionType description;
    @XmlElement(name = "Ext")
    protected ExtType ext;
    @XmlElement(name = "MasterSourceRef")
    protected AssetRefType masterSourceRef;
    @XmlAttribute(name = "uriId", required = true)
    protected String uriId;
    @XmlAttribute(name = "providerVersionNum")
    protected BigInteger providerVersionNum;
    @XmlAttribute(name = "internalVersionNum")
    protected BigInteger internalVersionNum;
    @XmlAttribute(name = "creationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "startDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlAttribute(name = "endDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateTime;
    @XmlAttribute(name = "notifyURI")
    @XmlSchemaType(name = "anyURI")
    protected String notifyURI;
    @XmlAttribute(name = "lastModifiedDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDateTime;
    @XmlAttribute(name = "eTag")
    protected String eTag;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "stateDetail")
    protected String stateDetail;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the alternateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternateIdType }
     * 
     * 
     */
    public List<AlternateIdType> getAlternateId() {
        if (alternateId == null) {
            alternateId = new ArrayList<AlternateIdType>();
        }
        return this.alternateId;
    }

    /**
     * Gets the value of the providerQAContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderQAContact() {
        return providerQAContact;
    }

    /**
     * Sets the value of the providerQAContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderQAContact(String value) {
        this.providerQAContact = value;
    }

    /**
     * Gets the value of the assetName property.
     * 
     * @return
     *     possible object is
     *     {@link AssetNameType }
     *     
     */
    public AssetNameType getAssetName() {
        return assetName;
    }

    /**
     * Sets the value of the assetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetNameType }
     *     
     */
    public void setAssetName(AssetNameType value) {
        this.assetName = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProduct(ProductType value) {
        this.product = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link ExtType }
     *     
     */
    public ExtType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtType }
     *     
     */
    public void setExt(ExtType value) {
        this.ext = value;
    }

    /**
     * Gets the value of the masterSourceRef property.
     * 
     * @return
     *     possible object is
     *     {@link AssetRefType }
     *     
     */
    public AssetRefType getMasterSourceRef() {
        return masterSourceRef;
    }

    /**
     * Sets the value of the masterSourceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetRefType }
     *     
     */
    public void setMasterSourceRef(AssetRefType value) {
        this.masterSourceRef = value;
    }

    /**
     * Gets the value of the uriId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUriId() {
        return uriId;
    }

    /**
     * Sets the value of the uriId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUriId(String value) {
        this.uriId = value;
    }

    /**
     * Gets the value of the providerVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProviderVersionNum() {
        return providerVersionNum;
    }

    /**
     * Sets the value of the providerVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProviderVersionNum(BigInteger value) {
        this.providerVersionNum = value;
    }

    /**
     * Gets the value of the internalVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInternalVersionNum() {
        return internalVersionNum;
    }

    /**
     * Sets the value of the internalVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInternalVersionNum(BigInteger value) {
        this.internalVersionNum = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateTime(XMLGregorianCalendar value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the notifyURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyURI() {
        return notifyURI;
    }

    /**
     * Sets the value of the notifyURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyURI(String value) {
        this.notifyURI = value;
    }

    /**
     * Gets the value of the lastModifiedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDateTime() {
        return lastModifiedDateTime;
    }

    /**
     * Sets the value of the lastModifiedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDateTime(XMLGregorianCalendar value) {
        this.lastModifiedDateTime = value;
    }

    /**
     * Gets the value of the eTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETag() {
        return eTag;
    }

    /**
     * Sets the value of the eTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETag(String value) {
        this.eTag = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the stateDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDetail() {
        return stateDetail;
    }

    /**
     * Sets the value of the stateDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDetail(String value) {
        this.stateDetail = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
