//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.core._3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Bucket are logical Asset containers associated with the {ProviderId} portion of the asset uriId.
 * 
 * <p>Java class for BucketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BucketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalStorage" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="AvailableStorage" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="InputProtocols" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalInputBandwidth" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="AvailableInputBandwidth" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="OutputProtocols" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalOutputBandwidth" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="AvailableOutputBandwidth" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="NumAssets" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="providerId" use="required" type="{urn:cablelabs:md:xsd:core:3.0}URIIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BucketType", propOrder = {
    "totalStorage",
    "availableStorage",
    "inputProtocols",
    "totalInputBandwidth",
    "availableInputBandwidth",
    "outputProtocols",
    "totalOutputBandwidth",
    "availableOutputBandwidth",
    "numAssets"
})
public class BucketType {

    @XmlElement(name = "TotalStorage")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalStorage;
    @XmlElement(name = "AvailableStorage")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger availableStorage;
    @XmlElement(name = "InputProtocols")
    protected String inputProtocols;
    @XmlElement(name = "TotalInputBandwidth")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalInputBandwidth;
    @XmlElement(name = "AvailableInputBandwidth")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger availableInputBandwidth;
    @XmlElement(name = "OutputProtocols")
    protected String outputProtocols;
    @XmlElement(name = "TotalOutputBandwidth")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalOutputBandwidth;
    @XmlElement(name = "AvailableOutputBandwidth")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger availableOutputBandwidth;
    @XmlElement(name = "NumAssets")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger numAssets;
    @XmlAttribute(name = "providerId", required = true)
    protected String providerId;

    /**
     * Gets the value of the totalStorage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalStorage() {
        return totalStorage;
    }

    /**
     * Sets the value of the totalStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalStorage(BigInteger value) {
        this.totalStorage = value;
    }

    /**
     * Gets the value of the availableStorage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvailableStorage() {
        return availableStorage;
    }

    /**
     * Sets the value of the availableStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvailableStorage(BigInteger value) {
        this.availableStorage = value;
    }

    /**
     * Gets the value of the inputProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputProtocols() {
        return inputProtocols;
    }

    /**
     * Sets the value of the inputProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputProtocols(String value) {
        this.inputProtocols = value;
    }

    /**
     * Gets the value of the totalInputBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalInputBandwidth() {
        return totalInputBandwidth;
    }

    /**
     * Sets the value of the totalInputBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalInputBandwidth(BigInteger value) {
        this.totalInputBandwidth = value;
    }

    /**
     * Gets the value of the availableInputBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvailableInputBandwidth() {
        return availableInputBandwidth;
    }

    /**
     * Sets the value of the availableInputBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvailableInputBandwidth(BigInteger value) {
        this.availableInputBandwidth = value;
    }

    /**
     * Gets the value of the outputProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputProtocols() {
        return outputProtocols;
    }

    /**
     * Sets the value of the outputProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputProtocols(String value) {
        this.outputProtocols = value;
    }

    /**
     * Gets the value of the totalOutputBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalOutputBandwidth() {
        return totalOutputBandwidth;
    }

    /**
     * Sets the value of the totalOutputBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalOutputBandwidth(BigInteger value) {
        this.totalOutputBandwidth = value;
    }

    /**
     * Gets the value of the availableOutputBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvailableOutputBandwidth() {
        return availableOutputBandwidth;
    }

    /**
     * Sets the value of the availableOutputBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvailableOutputBandwidth(BigInteger value) {
        this.availableOutputBandwidth = value;
    }

    /**
     * Gets the value of the numAssets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumAssets() {
        return numAssets;
    }

    /**
     * Sets the value of the numAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumAssets(BigInteger value) {
        this.numAssets = value;
    }

    /**
     * Gets the value of the providerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * Sets the value of the providerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderId(String value) {
        this.providerId = value;
    }

}
