//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.core._3;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="urn:cablelabs:md:xsd:core:3.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Trick Mode Restriction Type defines type and viewing rate scale restrictions. Note that, for each Trick Mode Restriction,
 * 		    all trick modes are initially permitted, less those explicitly excluded below. Restrictions on placements are applied to all
 * 		    AssetRefs. If restrictions are specified on both the placement and AssetRef, they are combined.&lt;/p&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for TrickModeRestrictionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrickModeRestrictionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrickModeExclusion" type="{urn:cablelabs:md:xsd:core:3.0}TrickModeExclusionType" maxOccurs="unbounded"/>
 *         &lt;element name="TrickModeRestrictionRule" type="{urn:cablelabs:md:xsd:core:3.0}ProcessRuleSelectorType" minOccurs="0"/>
 *         &lt;element name="Ext" type="{urn:cablelabs:md:xsd:core:3.0}ExtType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:cablelabs:md:xsd:core:3.0}EffectiveDatesDayTimeAttributeGroup"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrickModeRestrictionType", propOrder = {
    "trickModeExclusion",
    "trickModeRestrictionRule",
    "ext"
})
public class TrickModeRestrictionType {

    @XmlElement(name = "TrickModeExclusion", required = true)
    protected List<TrickModeExclusionType> trickModeExclusion;
    @XmlElement(name = "TrickModeRestrictionRule")
    protected ProcessRuleSelectorType trickModeRestrictionRule;
    @XmlElement(name = "Ext")
    protected ExtType ext;
    @XmlAttribute(name = "startDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlAttribute(name = "endDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateTime;
    @XmlAttribute(name = "mon")
    protected Boolean mon;
    @XmlAttribute(name = "tue")
    protected Boolean tue;
    @XmlAttribute(name = "wed")
    protected Boolean wed;
    @XmlAttribute(name = "thu")
    protected Boolean thu;
    @XmlAttribute(name = "fri")
    protected Boolean fri;
    @XmlAttribute(name = "sat")
    protected Boolean sat;
    @XmlAttribute(name = "sun")
    protected Boolean sun;
    @XmlAttribute(name = "startTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "duration")
    protected Duration duration;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the trickModeExclusion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trickModeExclusion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrickModeExclusion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrickModeExclusionType }
     * 
     * 
     */
    public List<TrickModeExclusionType> getTrickModeExclusion() {
        if (trickModeExclusion == null) {
            trickModeExclusion = new ArrayList<TrickModeExclusionType>();
        }
        return this.trickModeExclusion;
    }

    /**
     * Gets the value of the trickModeRestrictionRule property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessRuleSelectorType }
     *     
     */
    public ProcessRuleSelectorType getTrickModeRestrictionRule() {
        return trickModeRestrictionRule;
    }

    /**
     * Sets the value of the trickModeRestrictionRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessRuleSelectorType }
     *     
     */
    public void setTrickModeRestrictionRule(ProcessRuleSelectorType value) {
        this.trickModeRestrictionRule = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link ExtType }
     *     
     */
    public ExtType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtType }
     *     
     */
    public void setExt(ExtType value) {
        this.ext = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateTime(XMLGregorianCalendar value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the mon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMon() {
        if (mon == null) {
            return true;
        } else {
            return mon;
        }
    }

    /**
     * Sets the value of the mon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMon(Boolean value) {
        this.mon = value;
    }

    /**
     * Gets the value of the tue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTue() {
        if (tue == null) {
            return true;
        } else {
            return tue;
        }
    }

    /**
     * Sets the value of the tue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTue(Boolean value) {
        this.tue = value;
    }

    /**
     * Gets the value of the wed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWed() {
        if (wed == null) {
            return true;
        } else {
            return wed;
        }
    }

    /**
     * Sets the value of the wed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWed(Boolean value) {
        this.wed = value;
    }

    /**
     * Gets the value of the thu property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isThu() {
        if (thu == null) {
            return true;
        } else {
            return thu;
        }
    }

    /**
     * Sets the value of the thu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setThu(Boolean value) {
        this.thu = value;
    }

    /**
     * Gets the value of the fri property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFri() {
        if (fri == null) {
            return true;
        } else {
            return fri;
        }
    }

    /**
     * Sets the value of the fri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFri(Boolean value) {
        this.fri = value;
    }

    /**
     * Gets the value of the sat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSat() {
        if (sat == null) {
            return true;
        } else {
            return sat;
        }
    }

    /**
     * Sets the value of the sat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSat(Boolean value) {
        this.sat = value;
    }

    /**
     * Gets the value of the sun property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSun() {
        if (sun == null) {
            return true;
        } else {
            return sun;
        }
    }

    /**
     * Sets the value of the sun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSun(Boolean value) {
        this.sun = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
