//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:28:53 PM CET 
//


package cablelabs.md.xsd.offer._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import cablelabs.md.xsd.core._3.LocalizableStringType;


/**
 * Value denoting a path in the target catalog (may be localized to a target language).
 * 
 * <p>Java class for CategoryPathType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryPathType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:cablelabs:md:xsd:core:3.0>LocalizableStringType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryPathType")
public class CategoryPathType
    extends LocalizableStringType
{


}
