//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:28:53 PM CET 
//


package cablelabs.md.xsd.offer._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import cablelabs.md.xsd.core._3.AssetRefBaseType;
import cablelabs.md.xsd.core._3.AssetRefType;
import cablelabs.md.xsd.core._3.AssetType;


/**
 * An asset type used to group a title with one or more media assets.
 * 
 * <p>Java class for ContentGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentGroupType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:cablelabs:md:xsd:core:3.0}AssetType">
 *       &lt;sequence>
 *         &lt;element name="TitleRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="MovieRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="PreviewRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="PosterRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="BoxCoverRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="ThumbnailRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="BarkerRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType"/>
 *           &lt;element name="ContentRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefBaseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentGroupType", propOrder = {
    "titleRef",
    "movieRefOrPreviewRefOrPosterRef"
})
public class ContentGroupType
    extends AssetType
{

    @XmlElement(name = "TitleRef", required = true)
    protected AssetRefType titleRef;
    @XmlElementRefs({
        @XmlElementRef(name = "BarkerRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ContentRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PreviewRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ThumbnailRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BoxCoverRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MovieRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PosterRef", namespace = "urn:cablelabs:md:xsd:offer:3.0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends AssetRefBaseType>> movieRefOrPreviewRefOrPosterRef;

    /**
     * Gets the value of the titleRef property.
     * 
     * @return
     *     possible object is
     *     {@link AssetRefType }
     *     
     */
    public AssetRefType getTitleRef() {
        return titleRef;
    }

    /**
     * Sets the value of the titleRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetRefType }
     *     
     */
    public void setTitleRef(AssetRefType value) {
        this.titleRef = value;
    }

    /**
     * Gets the value of the movieRefOrPreviewRefOrPosterRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movieRefOrPreviewRefOrPosterRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovieRefOrPreviewRefOrPosterRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link AssetRefType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AssetRefBaseType>> getMovieRefOrPreviewRefOrPosterRef() {
        if (movieRefOrPreviewRefOrPosterRef == null) {
            movieRefOrPreviewRefOrPosterRef = new ArrayList<JAXBElement<? extends AssetRefBaseType>>();
        }
        return this.movieRefOrPreviewRefOrPosterRef;
    }

}
