//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:28:53 PM CET 
//


package cablelabs.md.xsd.offer._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import cablelabs.md.xsd.core._3.AssetRefType;
import cablelabs.md.xsd.core._3.ExtType;


/**
 * Provides presentation instructions specific to the VOD offer used to determine menu layout and corresponding UI items.
 * 
 * <p>Java class for PresentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CategoryRef" type="{urn:cablelabs:md:xsd:core:3.0}AssetRefType" minOccurs="0"/>
 *         &lt;element name="DisplayAsNew" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="DisplayAsLastChance" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="Priority" type="{urn:cablelabs:md:xsd:offer:3.0}PresentationPriorityType" minOccurs="0"/>
 *         &lt;element name="Ext" type="{urn:cablelabs:md:xsd:core:3.0}ExtType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentationType", propOrder = {
    "categoryRef",
    "displayAsNew",
    "displayAsLastChance",
    "priority",
    "ext"
})
public class PresentationType {

    @XmlElement(name = "CategoryRef")
    protected AssetRefType categoryRef;
    @XmlElement(name = "DisplayAsNew")
    protected Duration displayAsNew;
    @XmlElement(name = "DisplayAsLastChance")
    protected Duration displayAsLastChance;
    @XmlElement(name = "Priority")
    protected Integer priority;
    @XmlElement(name = "Ext")
    protected ExtType ext;

    /**
     * Gets the value of the categoryRef property.
     * 
     * @return
     *     possible object is
     *     {@link AssetRefType }
     *     
     */
    public AssetRefType getCategoryRef() {
        return categoryRef;
    }

    /**
     * Sets the value of the categoryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetRefType }
     *     
     */
    public void setCategoryRef(AssetRefType value) {
        this.categoryRef = value;
    }

    /**
     * Gets the value of the displayAsNew property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDisplayAsNew() {
        return displayAsNew;
    }

    /**
     * Sets the value of the displayAsNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDisplayAsNew(Duration value) {
        this.displayAsNew = value;
    }

    /**
     * Gets the value of the displayAsLastChance property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDisplayAsLastChance() {
        return displayAsLastChance;
    }

    /**
     * Sets the value of the displayAsLastChance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDisplayAsLastChance(Duration value) {
        this.displayAsLastChance = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link ExtType }
     *     
     */
    public ExtType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtType }
     *     
     */
    public void setExt(ExtType value) {
        this.ext = value;
    }

}
