//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.content._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import cablelabs.md.xsd.core._3.ExtType;


/**
 * <p>Java class for CopyControlInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CopyControlInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsCopyProtection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsCopyProtectionVerbose" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AnalogProtectionSystem" type="{urn:cablelabs:md:xsd:content:3.0}AnalogProtectionSystemType" minOccurs="0"/>
 *         &lt;element name="EncryptionModeIndicator" type="{urn:cablelabs:md:xsd:content:3.0}EncryptionModeIndicatorType" minOccurs="0"/>
 *         &lt;element name="ConstrainedImageTrigger" type="{urn:cablelabs:md:xsd:content:3.0}ConstrainedImageTriggerType" minOccurs="0"/>
 *         &lt;element name="CGMS_A" type="{urn:cablelabs:md:xsd:content:3.0}CGMSAType" minOccurs="0"/>
 *         &lt;element name="RequiresOutputControl" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Ext" type="{urn:cablelabs:md:xsd:core:3.0}ExtType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CopyControlInfoType", propOrder = {
    "isCopyProtection",
    "isCopyProtectionVerbose",
    "analogProtectionSystem",
    "encryptionModeIndicator",
    "constrainedImageTrigger",
    "cgmsa",
    "requiresOutputControl",
    "ext"
})
public class CopyControlInfoType {

    @XmlElement(name = "IsCopyProtection")
    protected Boolean isCopyProtection;
    @XmlElement(name = "IsCopyProtectionVerbose")
    protected Boolean isCopyProtectionVerbose;
    @XmlElement(name = "AnalogProtectionSystem")
    protected Short analogProtectionSystem;
    @XmlElement(name = "EncryptionModeIndicator")
    protected Short encryptionModeIndicator;
    @XmlElement(name = "ConstrainedImageTrigger")
    protected Short constrainedImageTrigger;
    @XmlElement(name = "CGMS_A")
    protected Short cgmsa;
    @XmlElement(name = "RequiresOutputControl")
    protected Boolean requiresOutputControl;
    @XmlElement(name = "Ext")
    protected ExtType ext;

    /**
     * Gets the value of the isCopyProtection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCopyProtection() {
        return isCopyProtection;
    }

    /**
     * Sets the value of the isCopyProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCopyProtection(Boolean value) {
        this.isCopyProtection = value;
    }

    /**
     * Gets the value of the isCopyProtectionVerbose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCopyProtectionVerbose() {
        return isCopyProtectionVerbose;
    }

    /**
     * Sets the value of the isCopyProtectionVerbose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCopyProtectionVerbose(Boolean value) {
        this.isCopyProtectionVerbose = value;
    }

    /**
     * Gets the value of the analogProtectionSystem property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAnalogProtectionSystem() {
        return analogProtectionSystem;
    }

    /**
     * Sets the value of the analogProtectionSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAnalogProtectionSystem(Short value) {
        this.analogProtectionSystem = value;
    }

    /**
     * Gets the value of the encryptionModeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEncryptionModeIndicator() {
        return encryptionModeIndicator;
    }

    /**
     * Sets the value of the encryptionModeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEncryptionModeIndicator(Short value) {
        this.encryptionModeIndicator = value;
    }

    /**
     * Gets the value of the constrainedImageTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getConstrainedImageTrigger() {
        return constrainedImageTrigger;
    }

    /**
     * Sets the value of the constrainedImageTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setConstrainedImageTrigger(Short value) {
        this.constrainedImageTrigger = value;
    }

    /**
     * Gets the value of the cgmsa property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCGMSA() {
        return cgmsa;
    }

    /**
     * Sets the value of the cgmsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCGMSA(Short value) {
        this.cgmsa = value;
    }

    /**
     * Gets the value of the requiresOutputControl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresOutputControl() {
        return requiresOutputControl;
    }

    /**
     * Sets the value of the requiresOutputControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresOutputControl(Boolean value) {
        this.requiresOutputControl = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link ExtType }
     *     
     */
    public ExtType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtType }
     *     
     */
    public void setExt(ExtType value) {
        this.ext = value;
    }

}
