//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.content._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import cablelabs.md.xsd.core._3.ExtType;


/**
 * Describes an encrypted asset.
 * 
 * <p>Java class for EncryptionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VendorName" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="ReceiverType" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType"/>
 *         &lt;element name="ReceiverVersion" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Encryption" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="EncryptionAlgorithm" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="EncryptionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EncryptionSystemInfo" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="EncryptionKeyBlock" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="Ext" type="{urn:cablelabs:md:xsd:core:3.0}ExtType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptionInfoType", propOrder = {
    "vendorName",
    "receiverType",
    "receiverVersion",
    "encryption",
    "encryptionAlgorithm",
    "encryptionDateTime",
    "encryptionSystemInfo",
    "encryptionKeyBlock",
    "ext"
})
public class EncryptionInfoType {

    @XmlElement(name = "VendorName")
    protected String vendorName;
    @XmlElement(name = "ReceiverType", required = true)
    protected String receiverType;
    @XmlElement(name = "ReceiverVersion")
    @XmlSchemaType(name = "unsignedInt")
    protected Long receiverVersion;
    @XmlElement(name = "Encryption")
    protected String encryption;
    @XmlElement(name = "EncryptionAlgorithm")
    protected String encryptionAlgorithm;
    @XmlElement(name = "EncryptionDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar encryptionDateTime;
    @XmlElement(name = "EncryptionSystemInfo")
    protected String encryptionSystemInfo;
    @XmlElement(name = "EncryptionKeyBlock")
    protected String encryptionKeyBlock;
    @XmlElement(name = "Ext")
    protected ExtType ext;

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the receiverType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverType() {
        return receiverType;
    }

    /**
     * Sets the value of the receiverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverType(String value) {
        this.receiverType = value;
    }

    /**
     * Gets the value of the receiverVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReceiverVersion() {
        return receiverVersion;
    }

    /**
     * Sets the value of the receiverVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReceiverVersion(Long value) {
        this.receiverVersion = value;
    }

    /**
     * Gets the value of the encryption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryption() {
        return encryption;
    }

    /**
     * Sets the value of the encryption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryption(String value) {
        this.encryption = value;
    }

    /**
     * Gets the value of the encryptionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionAlgorithm() {
        return encryptionAlgorithm;
    }

    /**
     * Sets the value of the encryptionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionAlgorithm(String value) {
        this.encryptionAlgorithm = value;
    }

    /**
     * Gets the value of the encryptionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEncryptionDateTime() {
        return encryptionDateTime;
    }

    /**
     * Sets the value of the encryptionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEncryptionDateTime(XMLGregorianCalendar value) {
        this.encryptionDateTime = value;
    }

    /**
     * Gets the value of the encryptionSystemInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionSystemInfo() {
        return encryptionSystemInfo;
    }

    /**
     * Sets the value of the encryptionSystemInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionSystemInfo(String value) {
        this.encryptionSystemInfo = value;
    }

    /**
     * Gets the value of the encryptionKeyBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionKeyBlock() {
        return encryptionKeyBlock;
    }

    /**
     * Sets the value of the encryptionKeyBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionKeyBlock(String value) {
        this.encryptionKeyBlock = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link ExtType }
     *     
     */
    public ExtType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtType }
     *     
     */
    public void setExt(ExtType value) {
        this.ext = value;
    }

}
