//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.content._3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cablelabs.md.xsd.content._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Preview_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Preview");
    private final static QName _Thumbnail_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Thumbnail");
    private final static QName _Barker_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Barker");
    private final static QName _Trick_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Trick");
    private final static QName _Poster_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Poster");
    private final static QName _Movie_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "Movie");
    private final static QName _ContentRefList_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "ContentRefList");
    private final static QName _BoxCover_QNAME = new QName("urn:cablelabs:md:xsd:content:3.0", "BoxCover");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cablelabs.md.xsd.content._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentRefListType }
     * 
     */
    public ContentRefListType createContentRefListType() {
        return new ContentRefListType();
    }

    /**
     * Create an instance of {@link PreviewType }
     * 
     */
    public PreviewType createPreviewType() {
        return new PreviewType();
    }

    /**
     * Create an instance of {@link MovieType }
     * 
     */
    public MovieType createMovieType() {
        return new MovieType();
    }

    /**
     * Create an instance of {@link BoxCoverType }
     * 
     */
    public BoxCoverType createBoxCoverType() {
        return new BoxCoverType();
    }

    /**
     * Create an instance of {@link TrickType }
     * 
     */
    public TrickType createTrickType() {
        return new TrickType();
    }

    /**
     * Create an instance of {@link PosterType }
     * 
     */
    public PosterType createPosterType() {
        return new PosterType();
    }

    /**
     * Create an instance of {@link ThumbnailType }
     * 
     */
    public ThumbnailType createThumbnailType() {
        return new ThumbnailType();
    }

    /**
     * Create an instance of {@link BarkerType }
     * 
     */
    public BarkerType createBarkerType() {
        return new BarkerType();
    }

    /**
     * Create an instance of {@link StillImageAssetType }
     * 
     */
    public StillImageAssetType createStillImageAssetType() {
        return new StillImageAssetType();
    }

    /**
     * Create an instance of {@link CopyControlInfoType }
     * 
     */
    public CopyControlInfoType createCopyControlInfoType() {
        return new CopyControlInfoType();
    }

    /**
     * Create an instance of {@link BitRateResolutionType }
     * 
     */
    public BitRateResolutionType createBitRateResolutionType() {
        return new BitRateResolutionType();
    }

    /**
     * Create an instance of {@link ContentAssetType }
     * 
     */
    public ContentAssetType createContentAssetType() {
        return new ContentAssetType();
    }

    /**
     * Create an instance of {@link AudioVideoAssetType }
     * 
     */
    public AudioVideoAssetType createAudioVideoAssetType() {
        return new AudioVideoAssetType();
    }

    /**
     * Create an instance of {@link EncryptionInfoType }
     * 
     */
    public EncryptionInfoType createEncryptionInfoType() {
        return new EncryptionInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreviewType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Preview")
    public JAXBElement<PreviewType> createPreview(PreviewType value) {
        return new JAXBElement<PreviewType>(_Preview_QNAME, PreviewType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThumbnailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Thumbnail")
    public JAXBElement<ThumbnailType> createThumbnail(ThumbnailType value) {
        return new JAXBElement<ThumbnailType>(_Thumbnail_QNAME, ThumbnailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BarkerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Barker")
    public JAXBElement<BarkerType> createBarker(BarkerType value) {
        return new JAXBElement<BarkerType>(_Barker_QNAME, BarkerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrickType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Trick")
    public JAXBElement<TrickType> createTrick(TrickType value) {
        return new JAXBElement<TrickType>(_Trick_QNAME, TrickType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PosterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Poster")
    public JAXBElement<PosterType> createPoster(PosterType value) {
        return new JAXBElement<PosterType>(_Poster_QNAME, PosterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MovieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "Movie")
    public JAXBElement<MovieType> createMovie(MovieType value) {
        return new JAXBElement<MovieType>(_Movie_QNAME, MovieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentRefListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "ContentRefList")
    public JAXBElement<ContentRefListType> createContentRefList(ContentRefListType value) {
        return new JAXBElement<ContentRefListType>(_ContentRefList_QNAME, ContentRefListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoxCoverType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cablelabs:md:xsd:content:3.0", name = "BoxCover")
    public JAXBElement<BoxCoverType> createBoxCover(BoxCoverType value) {
        return new JAXBElement<BoxCoverType>(_BoxCover_QNAME, BoxCoverType.class, null, value);
    }

}
