//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cablelabs:md:xsd:content:3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:cablelabs:md:xsd:content:3.0",prefix = "content")
})
package cablelabs.md.xsd.content._3;
