//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.content._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A base type for still image assets.
 * 
 * <p>Java class for StillImageAssetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StillImageAssetType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:cablelabs:md:xsd:content:3.0}ContentAssetType">
 *       &lt;sequence>
 *         &lt;element name="X_Resolution" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Y_Resolution" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Language" type="{urn:cablelabs:md:xsd:core:3.0}LanguageType" minOccurs="0"/>
 *         &lt;element name="Codec" type="{urn:cablelabs:md:xsd:content:3.0}ImageCodecType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StillImageAssetType", propOrder = {
    "xResolution",
    "yResolution",
    "language",
    "codec"
})
@XmlSeeAlso({
    BoxCoverType.class,
    PosterType.class,
    ThumbnailType.class
})
public class StillImageAssetType
    extends ContentAssetType
{

    @XmlElement(name = "X_Resolution")
    @XmlSchemaType(name = "unsignedInt")
    protected Long xResolution;
    @XmlElement(name = "Y_Resolution")
    @XmlSchemaType(name = "unsignedInt")
    protected Long yResolution;
    @XmlElement(name = "Language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String language;
    @XmlElement(name = "Codec")
    protected String codec;

    /**
     * Gets the value of the xResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getXResolution() {
        return xResolution;
    }

    /**
     * Sets the value of the xResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setXResolution(Long value) {
        this.xResolution = value;
    }

    /**
     * Gets the value of the yResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getYResolution() {
        return yResolution;
    }

    /**
     * Sets the value of the yResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setYResolution(Long value) {
        this.yResolution = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodec(String value) {
        this.codec = value;
    }

}
