//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 04:29:34 PM CET 
//


package cablelabs.md.xsd.content._3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes a trick-play asset.
 * 
 * <p>Java class for TrickType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrickType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:cablelabs:md:xsd:content:3.0}ContentAssetType">
 *       &lt;sequence>
 *         &lt;element name="BitRate" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="VendorName" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="VendorProduct" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType"/>
 *         &lt;element name="ForVersion" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType"/>
 *         &lt;element name="TrickMode" type="{urn:cablelabs:md:xsd:core:3.0}NonEmptyStringType"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrickType", propOrder = {
    "bitRate",
    "vendorName",
    "vendorProduct",
    "forVersion",
    "trickMode"
})
public class TrickType
    extends ContentAssetType
{

    @XmlElement(name = "BitRate", required = true)
    protected BigInteger bitRate;
    @XmlElement(name = "VendorName")
    protected String vendorName;
    @XmlElement(name = "VendorProduct", required = true)
    protected String vendorProduct;
    @XmlElement(name = "ForVersion", required = true)
    protected String forVersion;
    @XmlElement(name = "TrickMode", required = true)
    protected String trickMode;

    /**
     * Gets the value of the bitRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitRate() {
        return bitRate;
    }

    /**
     * Sets the value of the bitRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitRate(BigInteger value) {
        this.bitRate = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the vendorProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorProduct() {
        return vendorProduct;
    }

    /**
     * Sets the value of the vendorProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorProduct(String value) {
        this.vendorProduct = value;
    }

    /**
     * Gets the value of the forVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForVersion() {
        return forVersion;
    }

    /**
     * Sets the value of the forVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForVersion(String value) {
        this.forVersion = value;
    }

    /**
     * Gets the value of the trickMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrickMode() {
        return trickMode;
    }

    /**
     * Sets the value of the trickMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrickMode(String value) {
        this.trickMode = value;
    }

}
